[package]
name = "chip8"
version = "0.1.0"
authors = ["Wieds"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
device_query = "0.2.8"
sdl2 = "0.34.5"